# -*- coding: utf-8 -*-
"""api_live.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzDMgx2eNpYndbyRD_rjkY2p0ZWdT2cb
"""

equipos = {

    "Club America": "America",
    "Atlas": "Atlas",
    "Atletico San Luis": "Atlético San Luis",
    "Cruz Azul": "Cruz Azul",
    "Guadalajara Chivas": "Guadalajara",
    "FC Juarez": "FC Juárez",
    "Leon": "Leon",
    "Mazatlán": "Mazatlan",
    "Monterrey": "Monterrey",
    "Necaxa": "Necaxa",
    "CF Pachuca": "Pachuca",
    "Puebla": "Puebla",
    "U.N.A.M. - Pumas": "UNAM",
    "Club Queretaro": "Querétaro",
    "Santos Laguna": "Santos Laguna",
    "Tigres UANL": "UANL",
    "Club Tijuana": "Tijuana",
    "Toluca": "Toluca"

}

import requests

API_KEY = "7aa4e7acb35339c205c556be3eeb7f8d"

URL = "https://v3.football.api-sports.io/fixtures"

HEADERS = {
    "x-apisports-key": API_KEY
}


def obtener_partidos_en_vivo():

    params = {
        "live": "all"
    }

    r = requests.get(
        URL,
        headers=HEADERS,
        params=params,
        timeout=20
    )

    datos = r.json()

    return datos["response"]

def buscar_partido(partidos, local, visitante):

    for partido in partidos:

        home = partido["teams"]["home"]["name"]
        away = partido["teams"]["away"]["name"]

        home = equipos.get(home, home)
        away = equipos.get(away, away)
        print("API:", home, "-", away)
        print("MODELO:", local, "-", visitante)
        if home == local and away == visitante:

            return {

                "fixture": partido["fixture"]["id"],

                "minuto": partido["fixture"]["status"]["elapsed"],

                "estado": partido["fixture"]["status"]["short"],

                "goles_local": partido["goals"]["home"],

                "goles_visitante": partido["goals"]["away"]

            }

    return None

def obtener_estadisticas(fixture):

    url = "https://v3.football.api-sports.io/fixtures/statistics"

    r = requests.get(

        url,

        headers=HEADERS,

        params={

            "fixture": fixture

        },

        timeout=20

    )

    datos = r.json()

    if len(datos["response"]) == 0:
        return None

    return datos["response"]