# -*- coding: utf-8 -*-
"""api_live.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzDMgx2eNpYndbyRD_rjkY2p0ZWdT2cb
"""

equipos = {

    "Club America":"America",

    "Toluca":"Toluca",

    "Pumas UNAM":"UNAM",

    "Tigres UANL":"UANL",

    "FC Juarez":"FC Juárez",

    "Club Leon":"Leon",

    "Mazatlan FC":"Mazatlan"

}

import requests

API_KEY = "7aa4e7acb35339c205c556be3eeb7f8d"

URL = "https://v3.football.api-sports.io/fixtures"

HEADERS = {
    "x-apisports-key": API_KEY
}


def obtener_partidos_en_vivo():

    params = {
        "live": "all"
    }

    r = requests.get(
        URL,
        headers=HEADERS,
        params=params,
        timeout=20
    )

    datos = r.json()

    return datos["response"]

def buscar_partido(local, visitante):

    partidos = obtener_partidos_en_vivo()

    for partido in partidos:


        home = partido["teams"]["home"]["name"]
        away = partido["teams"]["away"]["name"]


        home = equipos.get(home, home)
        away = equipos.get(away, away)

        if home == local and away == visitante:

            return {

                "minuto": partido["fixture"]["status"]["elapsed"],

                "estado": partido["fixture"]["status"]["short"],

                "goles_local": partido["goals"]["home"],

                "goles_visitante": partido["goals"]["away"]

            }

    return None

