# -*- coding: utf-8 -*-
"""clases_funciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cNX9--M138Hb42qUYwOKYaOJo2GS9bKQ
"""

import numpy as np
from scipy.optimize import minimize
from scipy.stats import poisson
import matplotlib.pyplot as plt
import pandas as pd

def rhodixon(x,y,lamb,mu,phi):
      if x==0 and y==0:
        return 1-lamb*mu*phi
      elif x==0 and y==1:
        return 1+lamb*phi
      elif x==1 and y==0:
        return 1+mu*phi
      elif x==1 and y==1:
        return 1-phi
      else:
        return 1

def prob_a_american(proba_individual):

    decimal = 1/proba_individual

    if decimal >= 2:
        return round((decimal-1)*100)
    else:
        return round(-100/(decimal-1))
#%%

def score_matrix(prob,
                      equipo_local="Local",
                      equipo_visitante="Visitante",
                      mostrar_porcentaje=True,
                      cmap="Blues"):

    n = prob.shape[0]

    fig, ax = plt.subplots(figsize=(8,8))

    # Heatmap
    im = ax.imshow(prob, cmap=cmap)

    # Barra de color
    cbar = plt.colorbar(im)
    cbar.set_label("Probabilidad")

    # Diagonal
    ax.plot([-0.5,n-0.5],[-0.5,n-0.5],
            color="black",
            linewidth=2)

    # Texto en cada celda
    for i in range(n):
        for j in range(n):

            if i > j:
                color = "green"
            elif i == j:
                color = "black"
            else:
                color = "red"

            if mostrar_porcentaje:
                texto = f"{100*prob[i,j]:.1f}%"
            else:
                texto = f"{prob[i,j]:.3f}"

            ax.text(j,
                    i,
                    texto,
                    ha="center",
                    va="center",
                    color=color,
                    fontsize=8)

    ax.set_xticks(range(n))
    ax.set_yticks(range(n))

    ax.set_xlabel(f"Goles {equipo_visitante}", fontsize=12)
    ax.set_ylabel(f"Goles {equipo_local}", fontsize=12)

    ax.set_title(f"{equipo_local} vs {equipo_visitante}",
                 fontsize=16,
                 fontweight="bold")

    plt.tight_layout()

    return fig

class DixonColes:

    def __init__(self, xi=None):
        """
        xi=None  -> Dixon-Coles clásico
        xi=0.0065 -> Dixon-Coles con decaimiento temporal
        """

        self.xi = xi

        # parámetros del modelo
        self.ataque = None
        self.defensa = None
        self.gamma = None
        self.rho = None

        self.logLik = None
        self.resultado = None
        self.fitted = False
        if xi is None:
          self.model = "Dixon-Coles"
        else:
          self.model = "Dixon-Coles Time Decay"

        # información auxiliar
        self.equipos = None
        self.indice = None

    def fit(self, df):

        self.df = df.copy()
        self.n_partidos = len(df)

        equipos = np.sort(df["local"].unique())
        n = len(equipos)

        indice = {e: i for i, e in enumerate(equipos)}

        local_idx = df["local"].map(indice).to_numpy()
        visitante_idx = df["visitante"].map(indice).to_numpy()

        goles_local = df["goles_local"].to_numpy()
        goles_visitante = df["goles_visitante"].to_numpy()

        parametros = np.concatenate([
            np.random.uniform(0,0.5,n),
            np.random.uniform(-0.5,0,n),
            np.array([0.20,-0.05])
        ])



        # pesos temporales
        if self.xi is None:
            peso = np.ones(len(df))
        else:
            fecha = df["fecha"]
            ultima = fecha.max()
            tiempo = (ultima-fecha).dt.days.to_numpy()
            peso = np.exp(-self.xi*tiempo)



        def loglik(param):

            ataque = param[:n]
            defensa = param[n:2*n]

            gamma = param[-2]
            rho = param[-1]

            lambda_ = np.exp(
                ataque[local_idx] +
                defensa[visitante_idx] +
                gamma
            )

            mu = np.exp(
                ataque[visitante_idx] +
                defensa[local_idx]
            )

            tau = np.ones(len(df))

            m00 = (goles_local==0) & (goles_visitante==0)
            m01 = (goles_local==0) & (goles_visitante==1)
            m10 = (goles_local==1) & (goles_visitante==0)
            m11 = (goles_local==1) & (goles_visitante==1)

            tau[m00] = 1-lambda_[m00]*mu[m00]*rho
            tau[m01] = 1+lambda_[m01]*rho
            tau[m10] = 1+mu[m10]*rho
            tau[m11] = 1-rho

            tau = np.maximum(tau,1e-12)

            ll = (
                np.log(tau)
                + poisson.logpmf(goles_local,lambda_)
                + poisson.logpmf(goles_visitante,mu)
            )

            return -np.dot(peso,ll)

        def restriccion(param):
            return np.sum(param[:n])

        cons = {"type":"eq","fun":restriccion}

        bounds=[(-4,4)]*(2*n)
        bounds+=[(-1,1),(-0.2,0.2)]

        opt=minimize(
            loglik,
            parametros,
            method="SLSQP",
            constraints=cons,
            bounds=bounds
        )
        if not opt.success:
          raise RuntimeError(f"La optimización no convergió: {opt.message}")

        # guardar resultados

        self.ataque=dict(zip(equipos,opt.x[:n]))
        self.defensa=dict(zip(equipos,opt.x[n:2*n]))

        self.gamma=opt.x[-2]
        self.rho=opt.x[-1]

        self.logLik=-opt.fun
        self.resultado=opt
        self.fitted = True

        self.indice=indice
        self.n_equipos = n
        self.equipos = equipos
        self.parameters = pd.DataFrame({"Equipo": equipos,"Ataque": opt.x[:n],"Defensa": opt.x[n:2*n]})

        return self

    def expected_goals(
        self,
        equipo_local,
        equipo_visitante):

        if not self.fitted:
            raise ValueError(
                "Debe ejecutar fit() antes de usar expected_goals()."
            )

        if equipo_local not in self.ataque:
            raise ValueError(
                f"El equipo '{equipo_local}' no existe."
            )

        if equipo_visitante not in self.ataque:
            raise ValueError(
                f"El equipo '{equipo_visitante}' no existe."
            )

        lambda_ = np.exp(

            self.ataque[equipo_local]
            + self.defensa[equipo_visitante]
            + self.gamma

        )

        mu = np.exp(

            self.ataque[equipo_visitante]
            + self.defensa[equipo_local]

        )

        return lambda_, mu



    def predict(
        self,
        equipo_local,
        equipo_visitante,
        goles_max=7):

        if not self.fitted:
            raise ValueError(
                "Debe ejecutar fit() antes de usar predict()."
            )

        lambda_x, mu_y = self.expected_goals(
            equipo_local,
            equipo_visitante
        )

        prob=np.zeros((goles_max+1,goles_max+1))

        for i in range(goles_max+1):
            for j in range(goles_max+1):

                prob[i,j]=(
                    poisson.pmf(i,lambda_x)
                    *poisson.pmf(j,mu_y)
                    *rhodixon(i,j,lambda_x,mu_y,self.rho)
                )

        return prob

    def win_prob(self,
             local,
             visitante,
             goles_max):

        prob = self.predict(
                local,
                visitante,
                goles_max
            )

        prob_local = np.tril(prob, -1).sum()
        prob_empate = np.trace(prob)
        prob_visitante = np.triu(prob, 1).sum()

        tabla = pd.DataFrame([{
            local: prob_local,
            "Empate": prob_empate,
            visitante: prob_visitante
        }])

        tabla[f"Momio {local}"] = tabla[local].apply(prob_a_american)
        tabla["Momio Empate"] = tabla["Empate"].apply(prob_a_american)
        tabla[f"Momio {visitante}"] = tabla[visitante].apply(prob_a_american)

        return tabla

    def score_matrix(self,
                 local,
                 visitante,
                 goles_max=7):

        prob = self.predict(
            local,
            visitante,
            goles_max
        )
        return score_matrix(prob,local,visitante)



    def summary(self):

      return pd.DataFrame({

        "Parametro":[
            "Modelo",
            "Equipos",
            "Partidos",
            "Gamma",
            "Rho",
            "Xi",
            "LogLik",
            "Iteraciones",
            "Convergencia"
        ],

        "Valor":[
            self.model,
            self.n_equipos,
            self.n_partidos,
            self.gamma,
            self.rho,
            self.xi,
            self.logLik,
            self.resultado.nit,
            self.resultado.success
        ]}
      )
    @property
    def teams(self):
      if not self.fitted:
        raise ValueError(
            "Debe ejecutar fit() antes de consultar los equipos."
        )
      return self.equipos.tolist()

    def predict_score(
        self,
        local,
        visitante,
        goles_max=7):
      prob = self.predict(
      local,
      visitante,
      goles_max)
      return np.unravel_index(
          prob.argmax(),
          prob.shape)

    def __repr__(self):
      if not self.fitted:
        return f"<{self.model} (no entrenado)>"
      return (
        f"<{self.model}"
        f" | equipos={self.n_equipos}"
        f" | partidos={self.n_partidos}"
        f" | logLik={self.logLik:.2f}>"
    )